### ISSUE TITLE
So, when's the next one?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/monthly#5]
Let me suggest Wednesday 5th, right after our October business meeting.

**Comment by ronanyeah** [comment]
Yeah sounds good to me, I was actually going to do it week of the 19th but would be fun to have it after the meeting.

**Comment by sofer** [comment]
I am keen to sync business meetings and dinners, you know, er, just in case...

**Comment by hdrdavies** [comment]
can't make the 5th, sadly 😢

**Comment by msmichellegar** [comment]
I'm down! I agree with syncing the dinners and business meetings.

**Comment by ronanyeah** [comment]
OK then sounds like a plan. I'm thinking one of the Vietnamese places in Hoxton next. Then afterparty at Michelles. :smile:

**Comment by sofer** [comment]
@ronanyeah are you up for up for organising the RSVP list and booking the venue?

**Comment by sofer** [comment]
Next one on Wednesday 2nd.

@ronanyeah are you organising this one again?

**Comment by ronanyeah** [comment]
@sofer yes!
